/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class depspace_confidentiality_OREOrderScheme */

#ifndef _Included_depspace_confidentiality_OREOrderScheme
#define _Included_depspace_confidentiality_OREOrderScheme
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     depspace_confidentiality_OREOrderScheme
 * Method:    blkOreC
 * Signature: ([Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_depspace_confidentiality_OREOrderScheme_blkOreC
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
