#!/bin/bash

# Check parameters
if [ $# -lt 6 ] ; then
	echo "usage: $0 <client-id> <config-dir> <extension-code-dir> <executions> <extensible?> <num clients>"
	exit
fi

CLIENT_ID=$1
CFG_DIR=$2
EXT_DIR=$3
EXEC=$4
EXT=$5
NUM=$6

# Change directory
DIR=$(cd `dirname $0` && pwd)
cd $DIR/..

./jre1.8.0_144/bin/java -cp dist/DepSpace.jar:lib/SMaRt-eds.jar:lib/PVSS.jar:lib/commons-codec-1.5.jar:lib/core-0.1.4.jar:lib/groovy-1.0-JSR-06.jar:lib/netty-all-4.0.25.Final.jar:lib/slf4j-api-1.5.8.jar:lib/slf4j-jdk14-1.5.8.jar depspace.recipes.privacy.SecureDistributedQueue $CLIENT_ID $CFG_DIR $EXT_DIR $EXEC $EXT $NUM
