#!/bin/bash

# Check parameters
if [ $# -lt 3 ] ; then
	echo "usage: ... $0 <number of operations> <operation type> <field type> <size>"
	exit
fi

NUM_OPERATIONS=$1
OPERATION=$2
FIELD_TYPE=$3
SIZE=$4

# Change directory
DIR=$(cd `dirname $0` && pwd)
cd $DIR/..

#./java -Djava.library.path=./fastore -cp dist/DepSpace.jar:lib/SMaRt-eds.jar:lib/PVSS.jar:lib/commons-codec-1.5.jar:lib/core-0.1.4.jar:lib/groovy-1.0-JSR-06.jar:lib/netty-all-4.0.25.Final.jar:lib/slf4j-api-1.5.8.jar:lib/slf4j-jdk14-1.5.8.jar depspace.performance.Latency $NUM_CLIENTS $PROCESS_ID $NUM_OPERATIONS $OPERATION $FIELD_TYPE $SIZE
./java -Djava.library.path=./fastore -cp dist/DepSpace.jar:lib/SMaRt-eds.jar:lib/PVSS.jar:lib/commons-codec-1.5.jar:lib/core-0.1.4.jar:lib/groovy-1.0-JSR-06.jar:lib/netty-all-4.0.25.Final.jar:lib/slf4j-api-1.5.8.jar:lib/slf4j-jdk14-1.5.8.jar depspace.performance.Throughput $NUM_OPERATIONS $OPERATION $FIELD_TYPE $SIZE
